[package]
name = "health"
version = "0.1.0"
authors = ["Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
log = "0.3.0"
splinter = { path = "../../libsplinter" }

[features]
default = []

experimental = []
