name: O-4 Unit Test Splinter

on:
  pull_request:
    branches:
      - 0-4
env:
  CARGO_TERM_COLOR: always

jobs:
  unit_test_splinter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Unit Test Splinter
        run: just ci-test
