name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:

  unit_test_splinter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display envvars
        run: env

      - name: where am I
        run: pwd && ls -al

      - name: what is git
        run: git --version

      - name: show refs
        run: git show-ref

      - name: show
        run: git show

      - name: show tags
        run: git tag

      - name: git status
        run: git status && git describe --dirty

      - name: seriously fetch tags
        run: git fetch --tags --force

      - name: git status
        run: git status && git describe --dirty

      - name: get version with env
        env:
          VERSION: AUTO_STRICT
        run: ./bin/get_version

      - name: get version no env
        run: ./bin/get_version

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
